### ISSUE TITLE
How long does it take you to run MAML with higher?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-maml#9]
I was running my own code with torchmeta and an iteration takes like 1 sec:

```
| 7/10 [00:08<00:04,  1.34s/it]
```

```
80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | 8/10 [00:09<00:01,  1.01it/s]
```

with gpu of course.

So if I do 60K iterations that is 60K seconds which seems to be about 16 hours. 

That seems to be very time consuming, even though I am using a single meta-batch. 

[This repo says it takes (meta-lstm meta learner) ](https://github.com/markdtw/meta-learning-lstm-pytorch)2.5 hours:

> Training with the default settings takes ~2.5 hours on a single Titan Xp while occupying ~2GB GPU memory.

How long does your MAML take to run with torchmeta?

**Comment by renesax14** [comment]
discussion here: https://github.com/tristandeleu/pytorch-meta/issues/20

**Comment by renesax14** [comment]
I've ran the meta-lstm code before and it ran in under 4 hours...

**Comment by tristandeleu** [comment]
In my experiments, this implementation is indeed running 60k iterations in about 12-16h, so that seems about right (for Omniglot & MiniImagenet 5-way 1/5-shots, with the hyperparameters from the MAML paper). Also note that the script periodically does evaluation on the meta-validation split, which introduces an overhead. Using a single task per batch might give you a speedup compared to the hyperparameters from the paper (e.g. 4 tasks/batch for MiniImagenet IIRC).

However this implementation does not use higher, it uses the MetaModules from Torchmeta. From small scale experiments, it seems like using higher could be slightly faster than the MetaModule approach (because of some overhead in MetaModules, which hopefully is reduced in Torchmeta 1.4.6). You can take inspiration from [this example in Torchmeta](https://github.com/tristandeleu/pytorch-meta/tree/master/examples/maml-higher) to see how to combine this implementation with higher. I haven't compared this implementation against other MAML PyTorch implementations though, so I cannot guarantee that this is as efficient as it can be.
